---
- name: Install Homebrew casks
  homebrew_cask:
    update_homebrew: yes
    upgrade_all: yes
    name: "{{ item }}"
    state: present        
  with_items:
    - java

- name: Install Homebrew packages
  homebrew: 
    update_homebrew: yes
    name: "{{ item }}"
    state: present
  with_items:
    - maven
    - groovy
    - gradle
    - sbt
